defmodule TijaraTides.Domain do
  @moduledoc "Pure game state and rules. No processes, transport, or persistence."
  use Boundary,
    type: :strict,
    deps: [],
    exports: [
      ParticipationWorld,
      Warehouse,
      WarehouseWorld,
      OrderBook,
      OrderBookWorld,
      Auction,
      AuctionWorld,
      ChangeSet,
      LotIdsExhausted,
      EntityIndex,
      Game,
      Journal,
      Reporting,
      Account,
      AccountWorld,
      EmailIdentity,
      Commands,
      Ship,
      ShipWorld,
      CompanyFinance,
      CompanyFinanceWorld,
      Services.FinancialSettlement,
      Services.Bankruptcy,
      Services.Credit,
      PortCargoMarket,
      PortCargoMarketWorld,
      Fleet,
      Trading,
      CargoRules,
      Markets,
      Visibility,
      ReadState
    ]
end
